-- PRODUCT INFORMATION 

CREATE TABLE IF NOT EXISTS strains (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    type VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS brands (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT
);


CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255),
    description TEXT,
    unit VARCHAR(50),
    brand_id INTEGER NOT NULL REFERENCES brands(id) ON DELETE RESTRICT,
    strain_id INTEGER REFERENCES strains(id) ON DELETE RESTRICT,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE RESTRICT
);

-- INVENTORY 

CREATE TABLE IF NOT EXISTS inventory (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    location VARCHAR(255) DEFAULT 'backroom',
    quantity DECIMAL(10,3) NOT NULL DEFAULT 0,
    cost_price DECIMAL(10,2),
    supplier_name VARCHAR(255),
    last_updated TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id SERIAL PRIMARY KEY,
    inventory_id INTEGER NOT NULL REFERENCES inventory(id) ON DELETE CASCADE,
    movement_type VARCHAR(50) NOT NULL, -- 'restock', 'sale', 'adjustment', 'waste'
    quantity DECIMAL(10,3) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);
