-- PRODUCT INFORMATION 

CREATE TABLE IF NOT EXISTS strains (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    type VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS brands (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT
);


CREATE TABLE IF NOT EXISTS categories (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name TEXT,
    description TEXT
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255),
    description TEXT,
    price DECIMAL(10,2) NOT NULL,
    unit VARCHAR(50),
    brand_id INTEGER NOT NULL REFERENCES brands(id) ON DELETE RESTRICT,
    strain_id INTEGER REFERENCES strains(id) ON DELETE RESTRICT,
    category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE RESTRICT
);

-- INVENTORY 

CREATE TABLE IF NOT EXISTS inventory (
    id SERIAL PRIMARY KEY,
    product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    location VARCHAR(255) DEFAULT 'backroom',
    quantity INTEGER NOT NULL DEFAULT 0,
    cost_price DECIMAL(10,2),
    supplier_name VARCHAR(255),
    last_updated TIMESTAMP DEFAULT NOW()
);


